local map = vim.api.nvim_set_keymap
-- local map = vim.api.nvim_buf_set_keymap  -- Use this for buffer level

local options = { noremap = true }
map('n', '\\', ":LiveGrep <ENTER>", options)
map('n', '<C-\\>', ":Zen <ENTER>", options)
map('n', '<A-\\>', ":only <ENTER>", options)
-- map('n', '<C-n>', ":only <ENTER>", options)
map('n', '<F2>', ":Rename <ENTER>", options)
map('n', '<F3>', ":FormatCode <ENTER>", options)
map('n', '<A-SPACE>', ":", options)
map('n', '<C-SPACE>', ":Menu <ENTER>", options)
map('n', '<A-w>', ":Close <ENTER>", options)
map('n', '<C-w>', ":Hide <ENTER>", options)
map('n', '<A-f>', ":FindInFiles <ENTER>", options)
map('n', '<C-f>', ":FindInBuffer <ENTER>", options)
map('n', '<C-A-f>', ":FindResume <ENTER>", options)
map('n', '<C-g>', ":Git <ENTER>", options)
map('n', '<C-h>', ":Recent <ENTER>", options)
map('n', '<C-i>', ":FindInBuffers <ENTER>", options)
map('n', 'ga', ":CodeAction <ENTER>", options)
map('n', 'gb', ":Back", options)
map('n', 'gd', ":Definitions <ENTER>", options)
map('n', 'gh', ":Hover <ENTER>", options)
map('n', 'gi', ":Implementation <ENTER>", options)
map('n', 'gf', ":Peek <ENTER>", options)
map('n', 'gj', ":LSPDiagNext <ENTER>", options)
map('n', 'gk', ":LSPDiagPrev <ENTER>", options)
map('n', 'gl', ":LSPLineDiag <ENTER>", options)
map('n', 'go', ":Outline <ENTER>", options)
map('n', 'gr', ":References <ENTER>", options)
map('n', 'gs', ":Symbols <ENTER>", options)
map('n', 'gt', ":TypeDefs <ENTER>", options)
map('n', 'gv', ":Outline <ENTER>", options)
map('n', 'gx', ":CodeAction <ENTER>", options)
map('x', 'gx', ":CodeAction <ENTER>", options)
