local map = vim.api.nvim_set_keymap
-- local map = vim.api.nvim_buf_set_keymap  -- Use this for buffer level

-- Unset some default mappings
vim.keymap.del({ 'n' }, '<C-W>d')
vim.keymap.del({ 'n' }, '<C-W><C-D>')

local options = { noremap = true }
map('n', '\\', ":LiveGrep <ENTER>", options)
map('n', '<C-?>', ":LSPDiagWindow <ENTER>", options)
map('n', '<C-\\>', ":Zen <ENTER>", options)
map('n', '<A-\\>', ":RestoreSession <ENTER>", options)
map('n', '<ESC>', ":set hls! <ENTER>", options)
map('n', '<F2>', ":Rename <ENTER>", options)
map('n', '<F3>', ":FormatCode <ENTER>", options)
map('n', '<SPACE>', ":Telescope command_history <ENTER>", options)
map('n', '<A-SPACE>', ":", options)
map('n', '<C-SPACE>', ":Menu <ENTER>", options)
map('n', '<A-ENTER>', ":Split<ENTER>", options)
map('n', '<A-BS>', ":split <ENTER>", options)
map('n', '<TAB>', ":BufferPrev <ENTER>", options)
map('n', '<S-TAB>', ":BufferNext <ENTER>", options)
map('n', '<A-TAB>', ":wincmd W <ENTER>", options)
map('n', '<A-r>', ":WinResizerStartResize <ENTER>", options)
map('n', '<A-w>', ":Close <ENTER>", options)
map('n', '<C-a>', ":normal 0ggVG <ENTER>", options)
map('n', '<A-f>', ":FindInFiles <ENTER>", options)
map('n', '<C-f>', ":FindInBuffer <ENTER>", options)
map('n', '<C-A-f>', ":FindResume <ENTER>", options)
map('n', '<C-b>', ":Buffers <ENTER>", options)
map('n', '<C-d>', "dd", options)
map('n', '<C-g>', ":Git <ENTER>", options)
map('n', '<C-h>', ":Recent <ENTER>", options)
map('n', '<C-i>', ":FindInBuffers <ENTER>", options)
map('n', '<C-l>', ":Files <ENTER>", options)
map('n', '<C-m>', ":Marks <ENTER>", options)
map('n', '<C-n>', ":New <ENTER>", options)
map('n', '<C-p>', ":Telescope find_files <ENTER>", options)
map('n', '<C-t>', ":FloatermToggle terminal <ENTER>", options)
map('n', '<C-w>', ":Hide <ENTER>", options)
map('n', 'ga', ":CodeAction <ENTER>", options)
map('n', 'gb', ":Back", options)
map('n', 'gd', ":Definitions <ENTER>", options)
map('n', 'gh', ":Hover <ENTER>", options)
map('n', 'gi', ":Implementation <ENTER>", options)
map('n', 'gf', ":Peek <ENTER>", options)
map('n', 'gj', ":LSPDiagNext <ENTER>", options)
map('n', 'gk', ":LSPDiagPrev <ENTER>", options)
map('n', 'gl', ":LSPLineDiag <ENTER>", options)
map('n', 'go', ":Outline <ENTER>", options)
map('n', 'gr', ":References <ENTER>", options)
map('n', 'gs', ":Symbols <ENTER>", options)
-- map('n', 'gt', ":TypeDefs <ENTER>", options)
map('n', 'gt', ":Telescope treesitter <ENTER>", options)
map('n', 'gu', ":References <ENTER>", options)
map('n', 'gx', ":CodeAction <ENTER>", options)
map('n', 'gw', ":LSPDiagWindow <ENTER>", options)

map('n', '´', ":norm vi'<ENTER>", options)
map('n', '¨', ':norm vi"<ENTER>', options)
map('n', ')', ':norm vi)<ENTER>', options)
map('n', '(', ':norm vi(<ENTER>', options)
map('n', '{', ':norm vi{<ENTER>', options)
map('n', '}', ':norm vi}<ENTER>', options)
map('n', '[', ':norm vi[<ENTER>', options)
map('n', ']', ':norm vi]<ENTER>', options)

map('n', ';s', ":SaveSession <ENTER>", options)
map('n', ';r', ":RestoreSession <ENTER>", options)

map('n', ';h', ":norm _<ENTER>", options)
map('n', ';j', ":norm o<ENTER>", options)
map('n', ';k', ":norm ko<ENTER>", options)
map('n', ';l', ":norm $<ENTER>", options)

map('n', ';<TAB>', ":ArenaToggle <ENTER>", options)
map('n', ';;', ":norm _<ENTER>", options)

map('n', ';´', ":norm cs'`<ENTER>", options)
map('n', ',´', ":norm cs`'<ENTER>", options)

map('n', ',,', ":norm f,<ENTER>", options)
map('n', ',,s', ":SaveSession <ENTER>", options)
map('n', ',,1', ":SaveSession 1 <ENTER>", options)
map('n', ',,2', ":SaveSession 2 <ENTER>", options)
map('n', ',,3', ":SaveSession 3 <ENTER>", options)
map('n', ',,4', ":SaveSession 4 <ENTER>", options)
map('n', ',,5', ":SaveSession 5 <ENTER>", options)
map('n', ',,6', ":SaveSession 6 <ENTER>", options)
map('n', ',,7', ":SaveSession 7 <ENTER>", options)
map('n', ',,8', ":SaveSession 8 <ENTER>", options)
map('n', ',,9', ":SaveSession 9 <ENTER>", options)
map('n', ',,0', ":SaveSession 9 <ENTER>", options)
map('n', ';1', ":RestoreSession 1 <ENTER>", options)
map('n', ';2', ":RestoreSession 2 <ENTER>", options)
map('n', ';3', ":RestoreSession 3 <ENTER>", options)
map('n', ';4', ":RestoreSession 4 <ENTER>", options)
map('n', ';5', ":RestoreSession 5 <ENTER>", options)
map('n', ';6', ":RestoreSession 6 <ENTER>", options)
map('n', ';7', ":RestoreSession 7 <ENTER>", options)
map('n', ';8', ":RestoreSession 8 <ENTER>", options)
map('n', ';0', ":RestoreSession 9 <ENTER>", options)

map('i', '<C-e>', "<ESC>:Emmet<ENTER>", options)
map('i', '<C-v>', "<ESC>:norm p<ENTER>", options)
map('i', '<F3>', "<ESC>:FormatCode <ENTER>", options)

map('v', '<', "<gv", options)
map('v', '>', ">gv", options)

map('x', 'gx', ":CodeAction <ENTER>", options)
