local map = vim.api.nvim_set_keymap
-- local map = vim.api.nvim_buf_set_keymap  -- Use this for buffer level

local options = { noremap = true }
map('n', '<F2>', ":Rename <ENTER>", options)
map('n', '<F3>', ":FormatCode <ENTER>", options)
map('n', '<A-f>', ":FindInFiles <ENTER>", options)
map('n', '<C-f>', ":FindInBuffer <ENTER>", options)
map('n', '<C-A-f>', ":FindResume <ENTER>", options)
map('n', '<C-g>', ":Git <ENTER>", options)
map('n', '<C-h>', ":Recent <ENTER>", options)
map('n', '<C-i>', ":FindInBuffers <ENTER>", options)
-- map('x', 'ga', ":<c-u>Lspsaga range_code_action<cr>", options)
map('n', 'ga', ":CodeAction <ENTER>", options)
map('n', 'gb', ":Back", options)
map('n', 'gd', ":Peek <ENTER>", options)
map('n', 'gh', ":Hover <ENTER>", options)
map('n', 'gi', ":Implementation <ENTER>", options)
map('n', 'gf', "<cmd>Lspsaga lsp_finder<cr>", options)
map('n', 'gj', "<cmd>Lspsaga diagnostic_jump_next<cr>", options)
map('n', 'gk', "<cmd>Lspsaga diagnostic_jump_prev<cr>", options)
map('n', 'gl', "<cmd>Lspsaga show_line_diagnostics<cr>", options)
map('n', 'go', "SymbolsOutline", options)
map('n', 'gr', ":Telescope lsp_references<cr>", options)
map('n', 'gs', ":Telescope lsp_document_symbols<cr>", options)
map('n', 'gt', "<cmd>Lspsaga implement<cr>", options)
map('n', 'gv', "<cmd>Lspsaga preview_definition<cr>", options)
map('n', 'gx', "<cmd>Lspsaga code_action<cr>", options)
map('x', 'gx', ":<c-u>Lspsaga range_code_action<cr>", options)
-- map('n', '<C-u>',"<cmd>lua require('lspsaga.action').smart_scroll_with_saga(-1, '<c-u>')<cr>", {})
-- map('n', '<C-d>',"<cmd>lua require('lspsaga.action').smart_scroll_with_saga(1, '<c-d>')<cr>", {})
